version: '3.1'

services:

  influxdb:
    image: influxdb:1.7
    restart: always
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=inspii
      - INFLUXDB_USER_PASSWORD=inspii2020
    ports:
      - 8086:8086
      - 2003:2003
      - 8083:8083

  chronograf:
    image: chronograf:1.7
    restart: always
    ports:
      - 8888:8888