version: '3.1'

services:

  nats:
    image: nats
    command: -p 4222 -m 8222
    restart: always
    ports:
      - 4222:4222
      - 8222:8222

  nats-streaming:
    image: nats-streaming
    command: -p 4223 -m 8223
    restart: always
    ports:
      - 4223:4223
      - 8223:8223