apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    targetPort: 2379
    port: 22379
    nodePort: 32379
  - name: https
    protocol: TCP
    targetPort: 2380
    port: 22380
    nodePort: 32380
  selector:
    component: etcd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: default
  labels:
    component: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      component: etcd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        component: etcd
    spec:
      containers:
      - name: etcd
        image: xieyanze/etcd3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2379
        - containerPort: 2380
        env:
        - name: DATA_PATH
          value: /data
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - hostPath:
          path: /data/etcd
          type: ""
        name: data