apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: NodePort
  ports:
  - name: m
    protocol: TCP
    targetPort: 2003
    port: 22003
    nodePort: 32003
  - name: api
    protocol: TCP
    targetPort: 8086
    port: 28086
    nodePort: 30086
  - name: grpc
    protocol: TCP
    targetPort: 8083
    port: 28083
    nodePort: 30083
  - name: chronograf
    protocol: TCP
    targetPort: 8888
    port: 28888
    nodePort: 30888
  selector:
    component: influxdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: default
  labels:
    component: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        - containerPort: 2003
        - containerPort: 8083
        env:
        - name: INFLUXDB_GRAPHITE_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        - name: INFLUXDB_USER
          value: root
        - name: INFLUXDB_USER_PASSWORD
          value: root
        volumeMounts:
        - mountPath: /data
          name: data
      - name: chronograf
        image: chronograf:1.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
      volumes:
      - hostPath:
          path: /data/influxdb
          type: ""
        name: data