apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
spec:
  type: NodePort
  ports:
  - name: natsp
    protocol: TCP
    targetPort: 4222
    port: 24222
    nodePort: 30222
  - name: natsm
    protocol: TCP
    targetPort: 8222
    port: 28222
    nodePort: 30822
  selector:
    component: nats

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: default
  labels:
    component: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nats
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
      - name: nats
        image: nats
        args: ["-p","4222","-m","8222"]
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
        - containerPort: 8222
